//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel &apos;valise&apos; pour les trains NAT et Régio2N :
        /// - Détections d&apos;anomalies en temps réel, sur rame ou à distance
        /// - Affichage graphique avec dessins et couleurs
        /// - Simplifie la localisation des pannes pour les dépanneurs en dépôt
        /// - Assiste le pôle d&apos;appui conduite (Gare du Nord)
        /// - Chef de projet : gestion des stagiaires, gestion des tickets
        ///
        ///Banc de test réseaux pour le train Régio2N :
        /// - Basé sur le banc NAT développé précédemment
        /// - Simulation de 3x plus de réseaux et équipements
        /// - Logiciel [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string ABCPortageJobDescription {
            get {
                return ResourceManager.GetString("ABCPortageJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chef de projet informatique.
        /// </summary>
        public static string ABCPortageJobTitle {
            get {
                return ResourceManager.GetString("ABCPortageJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CENTRES D&apos;INTÉRÊT.
        /// </summary>
        public static string ActivitiesHeader {
            get {
                return ResourceManager.GetString("ActivitiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infographisme 3D
        ///Jeux vidéos et projets communautaires, compétitions.
        /// </summary>
        public static string ComputingActivityDescription {
            get {
                return ResourceManager.GetString("ComputingActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informatique.
        /// </summary>
        public static string ComputingActivityHeader {
            get {
                return ResourceManager.GetString("ComputingActivityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Programmation des microcontrôleurs, DSP, FPGA
        ///Réseaux informatiques, linux et informatique embarquée
        ///Applications pour PC et Linux embarqué
        ///Modélisation UML, gestion de sources (git)
        ///Support avec tickets, développement agile.
        /// </summary>
        public static string ComputingSkillsDescription {
            get {
                return ResourceManager.GetString("ComputingSkillsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CONTACT.
        /// </summary>
        public static string ContactHeader {
            get {
                return ResourceManager.GetString("ContactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FORMATION.
        /// </summary>
        public static string EducationHeader {
            get {
                return ResourceManager.GetString("EducationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Électronique.
        /// </summary>
        public static string ElectronicsHeader {
            get {
                return ResourceManager.GetString("ElectronicsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réalisation de schémas et routage de carte.
        /// </summary>
        public static string ElectronicsSkillsDescription {
            get {
                return ResourceManager.GetString("ElectronicsSkillsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à thomas.prioul@outlook.com.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anglais niveau C1/C2
        ///TOEIC : 990.
        /// </summary>
        public static string EnglishSkillLevel {
            get {
                return ResourceManager.GetString("EnglishSkillLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EXPÉRIENCE PROFESSIONNELLE.
        /// </summary>
        public static string ExperienceHeader {
            get {
                return ResourceManager.GetString("ExperienceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à THOMAS PRIOUL.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informatique industrielle.
        /// </summary>
        public static string IndustrialComputingHeader {
            get {
                return ResourceManager.GetString("IndustrialComputingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 23 ans
        ///Français
        ///Permis B.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IUT GEII de Tours.
        /// </summary>
        public static string IUTEducationDescription {
            get {
                return ResourceManager.GetString("IUTEducationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DUT GEII.
        /// </summary>
        public static string IUTEducationHeader {
            get {
                return ResourceManager.GetString("IUTEducationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ingénieur informatique industrielle.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langues.
        /// </summary>
        public static string LanguageSkillsHeader {
            get {
                return ResourceManager.GetString("LanguageSkillsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mailto:thomas.prioul@outlook.com.
        /// </summary>
        public static string MailToEmailAddress {
            get {
                return ResourceManager.GetString("MailToEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guitariste (8 ans)
        ///Batteur (débutant)
        ///Style de musique : du blues au métal, des 60&apos;s à aujourd&apos;hui.
        /// </summary>
        public static string MusicActivityDescription {
            get {
                return ResourceManager.GetString("MusicActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Musique.
        /// </summary>
        public static string MusicActivityHeader {
            get {
                return ResourceManager.GetString("MusicActivityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 06 35 91 42 86.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En alternance à Polytech Tours
        ///Option véhicules autonomes
        ///Major de la section informatique industrielle.
        /// </summary>
        public static string PolytechEducationDescription {
            get {
                return ResourceManager.GetString("PolytechEducationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ingénieur informatique industrielle.
        /// </summary>
        public static string PolytechEducationHeader {
            get {
                return ResourceManager.GetString("PolytechEducationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en poste en freelance pour la SNCF, je réalise des applications pour PC à destination de bancs de test ainsi qu&apos;à de l&apos;assistance au dépannage.
        ///
        ///Pour 2019 je cherche un poste plus tourné vers l&apos;électronique et le développement de produits à base de microcontrôleurs et/ou de cartes linux embarquées..
        /// </summary>
        public static string ProfileDescription {
            get {
                return ResourceManager.GetString("ProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PROFIL.
        /// </summary>
        public static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à COMPÉTENCES.
        /// </summary>
        public static string SkillsHeader {
            get {
                return ResourceManager.GetString("SkillsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Banc de test réseaux pour le train NAT :
        /// - Développement d&apos;architecture logicielle complexe
        /// - Modification code source FPGA en C (processeur NIOS)
        /// - Simulation en temps réel d&apos;équipements via un PC
        /// - Test des équipements dans leur environnement nominal
        /// - Réalisation de séquences (mise en service, arrêt d&apos;urgence...).
        /// </summary>
        public static string SNCFJobDescription {
            get {
                return ResourceManager.GetString("SNCFJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apprenti informatique industrielle.
        /// </summary>
        public static string SNCFJobTitle {
            get {
                return ResourceManager.GetString("SNCFJobTitle", resourceCulture);
            }
        }
    }
}
